name: Deploy

# Trigger the workflow on push and
# pull request events on the production branch
on:
  push:
    branches:
      - master
      - staging

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          port: ${{ secrets.STAGING_PORT }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSHKEY }}
          script: "cd /var/www/html/sfl-calculator-backend && ./.scripts/deploy.sh"
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          port: ${{ secrets.STAGING_PORT }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSHKEY }}
          script: "cd /var/www/html/sfl-calculator-backend && ./.scripts/deploy.sh"
